version: '2'
services:
  owl:
    build: ./
    ports:
      - "8064:8064"
    links:
      - database
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
      MONGODB_URI: mongodb://database:27017
      APP_DB: owl
      HOST: localhost
      PORT: 8064
      NODE_ENV: development

  database:
    image: mongo